export type ChurchMembers = {
  id: number;
  created: Date;
  updated: Date;
  birthDate?: Date;
  isActive: boolean;
  isBoardMember: boolean;
  bio?: string;
  tags?: string[];
  suffix?: string;
  email?: string;
  role: string;
  firstName: string;
  lastName: string;
  phoneNumber?: string;
  isLeader: boolean;
  headline?: string;
  image_banner?: string;
  image_profile?: string;
};
