import type { Metadata } from "next";
import { Providers } from "./provider";
import { fonts } from "./font";
import "@/styles/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={fonts.roboto.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
