# Generated by Django 5.1.3 on 2024-12-04 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_downloader', '0002_downloadrequest_error_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
