# Generated by Django 5.1.3 on 2024-12-14 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_downloader', '0003_alter_downloadrequest_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='downloadrequest',
            old_name='url',
            new_name='youtube_url',
        ),
    ]
