export enum PublicNavbarLabels {
  ABOUT = "About",
  MEDIA = "Media",
  GET_INVOLVED = "Get Involved",
  CONTACT_US = "Contact Us",
  MISSION_VISION = "Mission and Vision",
  MINISTRIES = "Ministries",
  LEADERSHIP = "Leadership",
  COMMUNITY = "Community",
  ANNOUNCEMENTS = "Announcements",
  INQUIRE = "Inquire",
  UPCOMING_EVENTS = "Upcoming Events",
  BIBLE_STUDY = "Bible Study",
  MUSIC = "Music",
}
